version: "3.9"
services:
  channel:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6060:6060/udp"
    networks:
      - espresso
    environment:
      - LISTEN_HOST=${LISTEN_HOST:-0.0.0.0}
      - LISTEN_PORT_NO=${LISTEN_PORT_NO:-6060}
networks:
  espresso:
    external: true
